#!/bin/bash
# ------------------------------------------------- #
# Deploy plugin files to plugin folder on specified server.
# Update the server variables for ssh access.

SSH_USER='hausXX';

SSH_SERVER='srv01'; # this should be mapped to your ssh config alias
REMOTE_PLUGIN_PATH='www/wp-content/plugins/site-widgets';

# No further adjustments are needed.
#
#
#
# ------------------------------------------------- #
# COMPILE & MINIFY
# ------------------------------------------------- #
#nvm use
npx mix --production


# ------------------------------------------------- #
# SYNC NECESSARY FILES TO SERVER
# ------------------------------------------------- #
# Sync files/folders to server
export LC_ALL=C
rsync -a ./* $SSH_USER@$SSH_SERVER:$REMOTE_PLUGIN_PATH --exclude=node_modules --exclude=.github --exclude=.idea --exclude=.gitignore --exclude=.nvmrc --exclude=composer.json --exclude=composer.lock --exclude=mix-manifest.json --exclude=package.json --exclude=info.json --exclude=package-lock.json --exclude=webpack.mix.js --exclude=README.md --exclude=deploy



# ------------------------------------------------- #
# CLEANUP
# ------------------------------------------------- #
# Beautify scripts again
npx mix


# ------------------------------------------------- #
# SUCCESS
# ------------------------------------------------- #
echo -e "\033[0;32m››› Deploy complete ‹‹‹"
